---
title: "Advent of Code 2018"
author: Anil Goyal
output:
  md_document:
    variant: markdown_github
---

```{r}
library(tidyverse)
library(unglue)
library(lubridate)
library(data.table)
```

### Day 1
### [--- Day 1: Chronal Calibration ---](https://adventofcode.com/2018/day/1)

#### Part-1
```{r}
input <- read_lines('input1.txt')

answer1_1 <- function(input){
  input %>% 
    as.integer() %>% 
    sum()
}

answer1_1(input)
```

#### Part-2
```{r}
answer1_2 <- function(input){
  freq <- input %>% as.integer()
  # initiate while loop
  while(!any(duplicated(cumsum(freq)))){
    freq <- append(freq, freq)
  }
  # final answer
  cumsum(freq)[which.max(duplicated(cumsum(freq)))]
}

answer1_2(input)
```


### Day-2
### [--- Day 2: Inventory Management System ---](https://adventofcode.com/2018/day/2)

#### Part-1
```{r}
input <- read_lines('input2.txt')

answer2_1 <- function(input){
  twos <- input %>% 
    str_split('') %>% 
    map_lgl(~ 2 %in% table(.x)) %>% 
    sum()
  
  threes <- input %>% 
    str_split('') %>% 
    map_lgl(~ 3 %in% table(.x)) %>% 
    sum() 
  
  twos * threes
}

answer2_1(input)
```

#### Part-2
```{r}
answer2_2 <- function(input){
  # modify input
  input <- input %>% str_split('')
  # initiate while loop to find i
  i <- 1
    while(!any(map_int(input[-i], ~sum(.x == input[[i]])) == 25)){
    i <- i+1
  }
  my_char <- input[[i]]
  my_char2 <- input[-i][[which.max(map_int(input[-i], ~ sum(.x == input[[i]])))]]
  # answer
  paste0(my_char[my_char == my_char2], collapse = '')
}

answer2_2(input)
```


### Day-3
### [--- Day 3: No Matter How You Slice It ---](https://adventofcode.com/2018/day/3)

#### Part-1
```{r}
input <- read_lines('input3.txt')

answer3_1 <- function(input){
  # patterns for ungluing details
  patterns <- '#{carpet_id=\\d+} @ {mar_w=\\d+},{mar_h=\\d+}: {carpet_w=\\d+}x{carpet_h=\\d+}'
  # database
  dat <- unglue_data(input, patterns = patterns, convert = TRUE)
  # define helper function
  carpet <- function(mw, mh, cw, ch){
    s_p <- complex(real = mw, imaginary = mh)
    s_ps <- seq(from=s_p, by = 1+0i, length.out=cw)
    map(s_ps, ~ seq(.x, by = 0+1i, length.out=ch)) %>% 
      unlist
  }
  
  # all carpets
  all_carps <- map(seq_len(nrow(dat)), ~carpet(dat$mar_w[.x], dat$mar_h[.x], dat$carpet_w[.x], dat$carpet_h[.x]))
  # answer
  all_carps %>% unlist %>% 
    table %>% 
    {which(. > 1)} %>% 
    length
}

answer3_1(input)
```

#### Part-2
```{r}
answer3_2 <- function(input){
  # patterns for ungluing details
  patterns <- '#{carpet_id=\\d+} @ {mar_w=\\d+},{mar_h=\\d+}: {carpet_w=\\d+}x{carpet_h=\\d+}'
  # database
  dat <- unglue_data(input, patterns = patterns, convert = TRUE)
  # define helper function
  carpet <- function(mw, mh, cw, ch){
    s_p <- complex(real = mw, imaginary = mh)
    s_ps <- seq(from=s_p, by = 1+0i, length.out=cw)
    map(s_ps, ~ seq(.x, by = 0+1i, length.out=ch)) %>% 
      unlist
  }
  
  # all carpets
  all_carps <- map(seq_len(nrow(dat)), ~carpet(dat$mar_w[.x], dat$mar_h[.x], dat$carpet_w[.x], dat$carpet_h[.x]))
  # Overlapping area
  overlap <- all_carps %>% unlist %>% 
    table %>% 
    {which(. > 1)} %>% 
    names() %>% 
    as.complex()
  
  # answer
  map_lgl(all_carps, ~ !any(.x %in% overlap)) %>% 
    which.max()
  
}

answer3_2(input)
```


### Day-4
### [--- Day 4: Repose Record --](https://adventofcode.com/2018/day/4)

#### Part-1
**Explanation** A solution using `dplyr` and `tidyr` strategy.  `data.table::rleid()` has also been used.
```{r}
input <- read_lines('input4.txt')

answer4_1 <- function(input){
  # patterns
  patterns <- c('[{time}] Guard #{guard_no=\\d+} {pat}',
                '[{time}] {pat}')
  # unglue data
  dat <- unglue::unglue_data(input, patterns = patterns) %>% 
    mutate(time = ymd_hm(time))
  
  # modify data to intermediate usable format
  dat2 <- dat %>% 
    arrange(time) %>% 
    fill(guard_no, .direction= 'down') %>% 
    mutate(duty = rleid(guard_no)) %>% 
    group_by(duty, guard_no) %>% 
    complete(time = seq.POSIXt(from = min(time), to = max(time), by = 'min')) %>% 
    fill(pat, .direction = 'down') %>% 
    ungroup %>% 
    filter(pat == 'falls asleep') %>% 
    mutate(minute = minute(time))  
  
  # guard number (strategy-1)
  guard <- dat2 %>% 
    group_by(guard_no) %>% 
    summarise(asleep = n()) %>% 
    filter(asleep == max(asleep)) %>% 
    pull(guard_no) %>% 
    as.numeric()
  # desired minute 
  minute <- dat2 %>% 
    filter(guard_no == guard) %>% 
    group_by(minute) %>% 
    summarise(times = n()) %>% 
    filter(times == max(times)) %>% 
    pull(minute)
  # answer
  guard * minute
}
answer4_1(input)
```

#### Part-2
```{r}
answer4_2 <- function(input){
  # patterns
  patterns <- c('[{time}] Guard #{guard_no=\\d+} {pat}',
                '[{time}] {pat}')
  # unglue data
  dat <- unglue::unglue_data(input, patterns = patterns) %>% 
    mutate(time = ymd_hm(time))
  
  # modify data to intermediate usable format
  dat2 <- dat %>% 
    arrange(time) %>% 
    fill(guard_no, .direction= 'down') %>% 
    mutate(duty = rleid(guard_no)) %>% 
    group_by(duty, guard_no) %>% 
    complete(time = seq.POSIXt(from = min(time), to = max(time), by = 'min')) %>% 
    fill(pat, .direction = 'down') %>% 
    ungroup %>% 
    filter(pat == 'falls asleep') %>% 
    mutate(minute = minute(time)) 
  
  # strategy-2 is easier
  dat2 %>% 
  group_by(guard_no, minute) %>% 
  summarise(times_asleep = n(), .groups = 'drop') %>% 
  filter(times_asleep == max(times_asleep)) %>% 
  {as.numeric(.$guard_no)*.$minute}
}

answer4_2(input)
```


### Day-5
### [--- Day 5: Alchemical Reduction ---](https://adventofcode.com/2018/day/5)

#### Part-1
```{r}
input <- read_lines('input5.txt')

answer5_1 <- function(input){
  # starting polymer
  polymer <- input
  # reactive polymers
  reactive_polymers <- c(paste0(letters, LETTERS), paste0(LETTERS, letters))
  # while loop to reduce polymer to unreactive polymer
  while(any(map_lgl(reactive_polymers , ~str_detect(polymer, .x)))){
    polymer <- reduce(reactive_polymers, 
                      .init = polymer,
                      ~str_remove_all(.x, .y))
  }
  # length of unreactive polymer
  nchar(polymer)
}

answer5_1(input)
```

#### Part-2
```{r}
answer5_2 <- function(input){
  # get polymer
  polymer <- input
  # reactive polymers list
  reactive_polymers <- c(paste0(letters, LETTERS), paste0(LETTERS, letters))
  # new reduction list
  reduction_list <- split(c(LETTERS, letters), rep(1:26, 2))
  # helper function this time
  my_fun <- function(polymer, reactive_polymers = reactive_polymers){
    while(any(map_lgl(reactive_polymers , ~str_detect(polymer, .x)))){
      polymer <- reduce(reactive_polymers, 
                        .init = polymer,
                        ~str_remove_all(.x, .y))
    }
    nchar(polymer)
  }
  # answer
  map(reduction_list, function(.a) reduce(.a, .init = polymer, ~str_remove_all(.x, .y))) %>% 
    map_int(my_fun, reactive_polymers) %>% 
    min()
}

answer5_2(input)
```


### Day-6
### [--- Day 6: Chronal Coordinates ---](https://adventofcode.com/2018/day/6)

#### Part-1
```{r}

```

#### Part-2
```{r}

```


### Day-7
### [](https://adventofcode.com/2018/day/7)

#### Part-1
```{r}

```

#### Part-2
```{r}

```
