---
title: "Advent Of Code 2022"
author: "Anil Goyal"
date: "2022-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(igraph)
library(unglue)
library(magrittr)
```

## Day - 1 [--- Day 1: Calorie Counting ---](https://adventofcode.com/2022/day/1) 
### Part-1

```{r}
input <- readLines('input1.txt') |>  as.numeric()

answer1_1 <- function(input){
  input |>  
    as.data.frame() |> 
    set_names('input') |> 
    group_by(grp = cumsum(is.na(input))) |> 
    summarise(food = sum(input, na.rm = T)) |> 
    slice_max(order_by = food) |> 
    pull(food)
}

answer1_1(input = input)

```

### Part-2
```{r}
answer1_2 <- function(input){
  input |> 
    as.numeric() |> 
    as.data.frame() |> 
    set_names('input') |> 
    group_by(grp = cumsum(is.na(input))) |> 
    summarise(food = sum(input, na.rm = T)) |> 
    slice_max(order_by = food, n=3) |> 
    pull(food) |> 
    sum()
}

answer1_2(input = input)
```
## Day-2 [--- Day 2: Rock Paper Scissors ---](https://adventofcode.com/2022/day/2)
### Part-1
```{r}
input <- readLines('input2.txt') %>% 
  as_tibble() %>% 
  separate(value, into = c('O', 'M'))

answer2_1 <- function(input){
  score_matrix <- rbind(A = c(3,6,0), B= c(0,3,6), C = c(6,0,3)) %>% as.matrix() %>% 
    `colnames<-`(c('X', "Y", "Z"))
  
  additional_scores <- c(1,2,3)
  
  input %>% 
    rowwise() %>% 
    mutate(score = score_matrix[O,M] + additional_scores[match(M, LETTERS[24:26])]) %>% 
    ungroup() %>% 
    summarise(sum(score))
}

answer2_1(input)
```
### Part-2
```{r}
answer2_2 <- function(input){
  score_matrix <- rbind(A = c(3,6,0), B= c(0,3,6), C = c(6,0,3)) %>% as.matrix() %>% 
    `colnames<-`(c('X', "Y", "Z"))
  
  additional_scores <- c(1,2,3)
  rev_matrix <- rbind(A = c('Z', 'X', 'Y'), B= c('X', 'Y', 'Z'), C = c('Y', 'Z', 'X')) %>% as.matrix() %>% 
    `colnames<-`(c('X', "Y", "Z"))
  
  input %>% 
    rowwise() %>% 
    mutate(strategy = rev_matrix[O, M],
           score = score_matrix[O, strategy] + additional_scores[match(strategy, LETTERS[24:26])]) %>% 
    ungroup() %>% 
    pull(score) %>% 
    sum()
}
answer2_2(input)
```


## Day-3 [--- Day 3: Rucksack Reorganization ---](https://adventofcode.com/2022/day/3)
### Part-1
```{r}
input <- readLines('input3.txt')

answer3_1 <- function(input){
  map2_chr(
    str_sub(input, start = 1, end = nchar(input)/2),
    str_sub(input, start = (nchar(input)/2)+1, end = -1L),
    ~ intersect(unlist(str_split(.x, '')), unlist(str_split(.y, '')))
  ) %>% 
    {sum(match(., letters), na.rm = T) + sum(match(., LETTERS) +26, na.rm = T)}
  
}

answer3_1(input)
```
### Part-2
```{r}
answer3_2 <- function(input){
    split(input, (seq_along(input) - 1) %/% 3) %>% 
    map_chr(~ intersect(
      intersect(
        unlist(
          str_split(.x[1], '')), 
        unlist(
          str_split(.x[2], ''))), 
      unlist(
        str_split(.x[3], '')))) %>% 
    {sum(match(., letters), na.rm = T) + sum(match(., LETTERS) +26, na.rm = T)}
}

answer3_2(input)
```
## Day-4 [--- Day 4: Camp Cleanup ---](https://adventofcode.com/2022/day/4)
### Part-1
```{r}
input <- readLines('input4.txt')
answer4_1 <- function(input){
  input %>% str_split(',') %>% 
  map(~ str_split(.x, '-') %>% unlist() %>% as.integer()) %>% 
  map_lgl(~ ((.x[1] >= .x[3]) & (.x[2] <= .x[4])) | ( (.x[1] <= .x[3]) & (.x[2] >= .x[4]) ) ) %>% 
  sum()
}

answer4_1(input)
```
### Part-2
This part is rather easy
```{r}
answer4_2 <- function(input){
  input %>% str_split(',') %>% 
  map(~ str_split(.x, '-') %>% unlist() %>% as.integer()) %>% 
  map_lgl(~ !((.x[4] < .x[1]) | (.x[3] > .x[2])) ) %>% 
  sum()
}

answer4_2(input)
```

## Day-5 [--- Day 5: Supply Stacks ---](https://adventofcode.com/2022/day/5)
### Part-1
```{r}
stacks <- read.fwf("input5.txt", widths = rep(4, 9), n = 8)

moves <- read.table("input5.txt", sep = " ", skip = 10)[, c(2, 4, 6)] %>% 
  set_names(c('cnt', 'from', 'to'))

answer5_1 <- function(stacks, moves){
  stacks %>% 
    as.data.frame() %>% 
    mutate(across(everything(), ~ str_remove_all(., '\\]'))) %>% 
    mutate(across(everything(), ~str_remove_all(., " "))) %>% 
    mutate(across(everything(), ~str_remove_all(., '\\['))) -> stacks_r
  
  stacks_r <- map(stacks_r, ~ .x[.x != ''])
  for(i in seq_len(nrow(moves))){
    from <- stacks_r[[moves$from[[i]]]]
    to <- stacks_r[[moves$to[[i]]]]
    cnt <- moves$cnt[[i]]
    elements_to_move <- rev(from[seq_len(cnt)])
    stacks_r[[moves$from[[i]]]] <- from[seq(cnt+1, length(from))]
    stacks_r[[moves$to[[i]]]] <- c(elements_to_move, to)
  }
  map_chr(stacks_r, ~ .x[1]) %>% paste0(collapse = '')
}

answer5_1(stacks, moves)

```

### Part-2
```{r}
answer5_2 <- function(stacks, moves){
  stacks %>% 
    as.data.frame() %>% 
    mutate(across(everything(), ~ str_remove_all(., '\\]'))) %>% 
    mutate(across(everything(), ~str_remove_all(., " "))) %>% 
    mutate(across(everything(), ~str_remove_all(., '\\['))) -> stacks_r
  
  stacks_r <- map(stacks_r, ~ .x[.x != ''])
  for(i in seq_len(nrow(moves))){
    from <- stacks_r[[moves$from[[i]]]]
    to <- stacks_r[[moves$to[[i]]]]
    cnt <- moves$cnt[[i]]
    elements_to_move <- from[seq_len(cnt)]
    stacks_r[[moves$from[[i]]]] <- from[seq(cnt+1, length(from))]
    stacks_r[[moves$to[[i]]]] <- c(elements_to_move, to)
  }
  map_chr(stacks_r, ~ .x[1]) %>% paste0(collapse = '')
}

answer5_2(stacks, moves)
```


## Day-6 [--- Day 6: Tuning Trouble ---](https://adventofcode.com/2022/day/6)
```{r}
input <- readLines('input6.txt') |> str_split('') |> unlist()

answer6 <- function(input, n= 4){
  i <- 1
  while (length(unique(input[i:(i+n-1)])) < n) {
    i <- i + 1  
  }
  i+n-1
}
# Part-1
answer6(input=input, n=4)
# part-2
answer6(input=input, n=14)
```

## Day-7 []()
### Part-1

## Day-8 [--- Day 8: Treetop Tree House ---](https://adventofcode.com/2022/day/8)
### Part-1
```{r}
input <- readLines('input8.txt')
answer8_1 <- function(input){
  
  len <- nchar(input[1])
  
  input <- input %>% 
    str_split('' ) %>% 
    unlist() %>% 
    as.integer()
  
  
  names <- complex(real = ((seq_along(input) - 1) %/% len) +1, imaginary = ((seq_along(input) - 1) %% len) +1) %>% 
    as.character()
  
  names(input) <- names
  
  
  res <- c()
  max_fun <- function(x){if(is.null(x)){-1} else {max(input[as.character(x)])}}
  
  for(i in seq_along(input)){
    
    j <- as.complex(names[i])
    
    left <- if(Re(j)==1){NULL}else{complex(real = seq(Re(j)-1), imaginary = Im(j))}
    top <- if(Im(j) == 1){NULL}else{complex(real = Re(j), imaginary = seq(Im(j) - 1))}
    right <- if(Re(j)==99){NULL}else{complex(real = seq(from = Re(j)+1, 99, 1), imaginary = Im(j))}
    bottom <- if(Im(j) == 99){NULL}else{complex(real = Re(j), imaginary = seq(from = Im(j)+1, 99, 1))}
    
    left_max <- max_fun(left)
    top_max <- max_fun(top)
    right_max <- max_fun(right)
    bottom_max <- max_fun(bottom)
    
    all_max <- c(left_max, top_max, right_max, bottom_max)
    cur <- any(all_max < input[i])
    res <- c(res, cur)
  }
  
  sum(res)
}
answer8_1(input)
```
### Part-2
```{r}
answer8_2 <- function(input){
  
}
```


## Day-12 [--- Day 12: Hill Climbing Algorithm ---](https://adventofcode.com/2022/day/12)
### Part-1
```{r}
input12 <- readLines('input12.txt')

answer12_1 <- function(input){

  len <- nchar(input[1])
  input %>% 
    str_split('') %>% 
    unlist() %>% 
    {seq_along(.) -1} %>% 
    {(. %% len)+(. %/% len)*(0+1i)} -> input_nodes
  
  names(input_nodes) <- input %>% 
    str_split('') %>% 
    unlist()
  
  input_nodes1 <- input_nodes
  from_node <- input_nodes1[names(input_nodes1) == 'S']
  to_node <- input_nodes1[names(input_nodes1) == 'E']
  
  names(input_nodes) <- ifelse(names(input_nodes) == 'S', 
                               'a', 
                               ifelse(names(input_nodes) == 'E', 
                                      'z',
                                      names(input_nodes)
                               )
  )
  
  names(input_nodes) <- match(names(input_nodes), letters)
  
  cross2(input_nodes, input_nodes, .filter = function(x, y) (Mod(x-y)>1 | x==y) ) %>% 
    map_df(setNames, c('from', 'to')) %>% 
    filter(as.integer(names(input_nodes)[match(to, input_nodes)]) - 
             as.integer(names(input_nodes)[match(from, input_nodes)]) <= 1) %>% 
    graph_from_data_frame() -> gg
  
  from_g <- V(gg) %>% names() %>% as.complex() %>% {which(. == from_node)}
  to_g <- V(gg) %>% names() %>% as.complex() %>% {which(. == to_node)}
  
  distances(gg, v = from_g, to_g, mode = 'out', algorithm = 'unweighted')
}
answer12_1(input12)
```

### Part-2
```{r}
answer12_2 <- function(input){
  len <- nchar(input[1])
  input %>% 
    str_split('') %>% 
    unlist() %>% 
    {seq_along(.) -1} %>% 
    {(. %% len)+(. %/% len)*(0+1i)} -> input_nodes
  
  names(input_nodes) <- input %>% 
    str_split('') %>% 
    unlist()
  
  input_nodes1 <- input_nodes
  
  to_node <- input_nodes1[names(input_nodes1) == 'E']
  from_nodes <- input_nodes1[names(input_nodes1) == 'a']
  
  names(input_nodes) <- ifelse(names(input_nodes) == 'S', 
                               'a', 
                               ifelse(names(input_nodes) == 'E', 
                                      'z',
                                      names(input_nodes)
                               )
  )
  
  names(input_nodes) <- match(names(input_nodes), letters)
  
  cross2(input_nodes, input_nodes, .filter = function(x, y) (Mod(x-y)>1 | x==y) ) %>% 
    map_df(setNames, c('from', 'to')) %>% 
    filter(as.integer(names(input_nodes)[match(to, input_nodes)]) - 
             as.integer(names(input_nodes)[match(from, input_nodes)]) <= 1) %>% 
    graph_from_data_frame() -> gg
  
  
  to_g <- V(gg) %>% names() %>% as.complex() %>% {which(. == to_node)}
  
  from_g2 <- V(gg) %>% names() %>% as.complex() %>% {which(. %in% from_nodes)}
  
  distances(gg, v = from_g2, to_g, mode = 'out', algorithm = 'unweighted') %>% min()
}
answer12_2(input12)
```

## Day-15 [--- Day 15: Beacon Exclusion Zone ---](https://adventofcode.com/2022/day/15)
### Part-1
```{r}
input <- readLines('input15.txt')

answer15_1 <- function(input){
  patterns <- "Sensor at x={s_x}, y={s_y}: closest beacon is at x={b_x}, y={b_y}"
  
  unglue::unglue_data(input, patterns = patterns, convert = TRUE) %>% 
    as_tibble() %>% 
    transmute(sensor = s_x+(s_y*1i),
           beacon = b_x + b_y*1i,
           dist = sensor-beacon,
           dist = abs(Re(dist))+abs(Im(dist))) -> data
  
  y_pos <- 2000000
  
  data %>% 
    mutate(dist2 = ifelse(dist - abs(Im(sensor)-y_pos)<0, 0, dist - abs(Im(sensor)-y_pos)),
           from = complex(real = Re(sensor) - dist2, imaginary = y_pos),
           from = Re(ifelse(from %in% data$beacon, from +1, from)),
           to = complex(real = Re(sensor) + dist2, imaginary = y_pos),
           to = Re(ifelse(to %in% data$beacon, to -1, to))) %>% 
    filter(to>=from) %>% 
    arrange(from) %>% 
    mutate(dummy = cummax(lag(to, default = first(to)))) %>% 
    filter(to > dummy | row_number() ==1) %$% 
    {length(seq(from=min(from), max(to), by=1))-1}
}
  
answer15_1(input)
```
### Part-2
```{r}

```

